### PR TITLE
Set babel conf for webpack tree shaking

### PR DESCRIPTION
**Pull request by micaelmbagira**

### CODE REVIEW

**Comment by zckrs** [comment]
Can we define a default env to avoid some BABEL_ENV = 'dev' and keep only one  BABEL_ENV = 'production' ?

**Comment by zckrs** [comment]
https://babeljs.io/docs/usage/babelrc/

> The env key will be taken from process.env.BABEL_ENV, when this is not available then it uses process.env.NODE_ENV if even that is not available then it defaults to "development".

If you replace in babelrc 'dev' by 'development' we don't need specify babel_env except for production

**Comment by zckrs** [comment]
Last point
Maybe we should use a uniq env variable: NODE_ENV

**Comment by micaelmbagira** [comment]
👍

**Pull request merged**
