### PR TITLE
Fixed duplication of vendor scripts in webpack build

### PR DESCRIPTION
**Pull request by vedmaque**
Resolves https://github.com/FountainJS/generator-fountain-webapp/issues/118

### CODE REVIEW

**Comment by facultymatt** [comment]
+1 to get this released!

**Comment by zckrs** [comment]
Confirmed.

In [past PR](https://github.com/FountainJS/generator-fountain-webpack/pull/35/files) we split output file.

**Comment by zckrs** [comment]
@vedmaque can you provide some explanations (or a doc link) on your fix with `CommonsChunkPlugin` please :-) ?

**Comment by zckrs** [comment]
Anyway good job :clap:  and thank you  :+1:

**Comment by vedmaque** [comment]
[http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin](http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin)

Probably, should add `minChunks: Infinity` option, but i'm not sure. 

ps. Actually it works like black box. Yes, it has documentation, but you will never know what would happen if you change some params :sob:

**Pull request merged**
